### ISSUE TITLE
Flate2 with zlib-rs fails to parse file that works with zlib-ng ("corrupt gzip stream does not have a matching checksum" or "numeric field was not a number:  when getting cksum for ")

### ISSUE THREAD

**Issue by VorpalBlade** [trifectatechfoundation/zlib-rs#213]
I'm processing archive files from Debian and I get the following error when processing the inner tar archive for `firmware-misc-nonfree_1%3a20230625-2+rpt3_all.deb`:

```
numeric field was not a number:  when getting cksum for 
```

(Yes that seems like it is trying to format the empty string.)

This archive works when using zlib-ng.

When I do a smaller test case I get this error instead:

```
thread 'main' panicked at src/main.rs:42:25:
called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "corrupt gzip stream does not have a matching checksum" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1102:23
   4: flate2_reproducer::parse_file::{{closure}}
             at ./src/main.rs:42:20
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:305:13
   6: core::option::Option<T>::map
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:1110:29
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/adapters/map.rs:108:26
   8: flate2_reproducer::main
             at ./src/main.rs:12:18
   9: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I have attached a reproducer project for the latter error (ignore some of the code comments in the file, they are from an earlier reproducer for a different flate2 bug, and I forgot to update the comments):
[flate2-reproducer.tar.gz](https://github.com/user-attachments/files/17270816/flate2-reproducer.tar.gz)

Please do note that as the name "firmware-misc-nonfree" implies, actually including this file as a test file in your repository might be tricky! I'm not a lawyer etc. And it is large, at 23 MB.

Versions:
* rustc 1.81
* flate2 1.0.30
* zlib-rs 0.3.1

**Comment by folkertdev** [comment]
thanks for reporting! 

I've fixed the issue, though a new release might have to wait a couple of weeks because a bunch of us are traveling.

**Comment by VorpalBlade** [comment]
That was quick, I will have to patch the dependency and test to see if I find any more archives it fails on.

I'm a bit surprised that making a release is difficult. You don't use CI automation for this? I use https://github.com/MarcoIeni/release-plz for this myself. Fully automated releases (including generating changelogs from the conventional commit messages).
